### PR TITLE
Fix panic when decoding CBOR nil to `*cbor.SimpleValue`

### LINKED ISSUE #460: bug: updated fuzzing detected panic while decoding CBOR nil or CBOR undefined to `*cbor.SimpleValue`
Decoding CBOR nil or CBOR undefined to `*cbor.SimpleValue` panics.

This crash bug was detected while adding more tests and updating fuzzer.

As mentioned in docs for `cbor.Unmarshal`, decoding CBOR nil or CBOR undefined to any Go pointer value should reset the pointer to nil.

```
// To unmarshal CBOR into a pointer, Unmarshal sets the pointer to nil
// if CBOR data is null (0xf6) or undefined (0xf7).  Otherwise, Unmarshal
// unmarshals CBOR into the value pointed to by the pointer.  If the
// pointer is nil, Unmarshal creates a new value for it to point to.
```

### PR DESCRIPTION
**Pull request by fxamacker**
Closes #460 

Unmarshalling CBOR nil or CBOR undefined into a Go pointer should always set the pointer to nil.

This PR:

- fixes panic when unmarshalling CBOR nil or CBOR undefined into `*cbor.SimpleValue` by setting the pointer to nil.
- adds more tests for decoding to uninitialized and initialized pointer values.

Separately (not part of this PR), the fuzzer was updated to attempt unmarshaling directly to `*cbor.SimpleValue`.

### CODE REVIEW

File: decode.go [hunk 1]
```diff
@@ -834,6 +834,13 @@ const (
 // and does not perform bounds checking.
 func (d *decoder) parseToValue(v reflect.Value, tInfo *typeInfo) error { //nolint:gocyclo
 
+	// Decode CBOR nil/undefined to pointer value by setting pointer value to nil.
```
Comment (x448) [inline decode.go:837]: "CBOR nil/undefined" sounds confusing, like dividing nil by undefined.  :laughing:

**Review by x448 — APPROVED** [review]
Great catch!

Given this fixes a decoder panic, are you going to release v2.5.1 or v2.6.0 with this fix soon?

How long was this fix fuzz tested in case we want to use it in production before next release tag?

**Comment by fxamacker** [comment]
@x448 

> Given this fixes a decoder panic, are you going to release v2.5.1 or v2.6.0 with this fix soon?

Probably v2.6.0 because they are new features merged and fuzzed already.

> How long was this fix fuzz tested in case we want to use it in production before next release tag?

It's best to wait for release tag before deploying to production, but feel free to try using main branch anytime for tests, etc.

BTW, I have at least 1 more bugfix to merge before tagging.
