### PR TITLE
Make Decoder.Decode() return io.UnexpectedEOF instead of io.EOF if CBOR data item is truncated

### LINKED ISSUE #378: bug: Decoder.Decode() should return io.UnexpectedEOF instead of io.EOF if CBOR data item is truncated
If CBOR data item is truncated at EOF, then Decoder.Decode() should return `io.UnexpectedEOF` instead of `io.EOF`.

### PR DESCRIPTION
**Pull request by fxamacker**
If CBOR data item is truncated at EOF, then Decoder.Decode() should return io.UnexpectedEOF instead of io.EOF.

Closes #378

### CODE REVIEW

File: stream.go [hunk 1]
```diff
@@ -31,22 +32,30 @@ func (dec *Decoder) Decode(v interface{}) error {
...
 		// Need to read more data.
-		if n, e := dec.read(); n == 0 {
-			return e
+		if n, err := dec.read(); n == 0 {
+			if err == io.EOF {
+				err = io.ErrUnexpectedEOF
+			}
+			return err
 		}
-		return dec.Decode(v)
```
Comment (x448) [inline stream.go:47]: Good idea to replace recursive call with for-loop. 👍

**Review by x448 — APPROVED** [review]
